"""empty message

Revision ID: b7091f42b66c
Revises: 624c56aed148
Create Date: 2022-10-24 21:09:17.760604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7091f42b66c'
down_revision = '624c56aed148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'position', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'employee', ['position_id'], ['id'])
    # ### end Alembic commands ###
